repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
    # Run the ruff linter and formatter using just command
    - id: ruff-check
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0  
  hooks:
  - id: check-toml
  - id: no-commit-to-branch

- repo: local
  hooks:
  -   id: run-security-scan
      name: run-security-scan
      entry: python3 -m src.hooks.cli run_scan --verbose
      language: python
      additional_dependencies: [aiohttp, anyio, gitpython, pyyaml, requests, prettytable, proxy-py, presidio_analyzer]
      stages: [pre-commit]
      verbose: true
      require_serial: true

  -   id: validate-security-scan
      name: validate-security-scan
      entry: python3 -m src.hooks.cli validate_scan --verbose
      language: python
      additional_dependencies: [aiohttp, anyio, gitpython, pyyaml, requests, prettytable, proxy-py, presidio_analyzer]
      stages: [commit-msg]
      verbose: true
  