repos:
  - repo: https://github.com/uktrade/github-standards
    rev: main # This should be the latest github released tag, see https://github.com/uktrade/github-standards/releases for the latest tag
    hooks:
      - id: validate-security-scan
        verbose: true # This is helpful for debugging initial setup, it can be removed when the hooks are verified as working in your repositoty
        args: [-v] # This is helpful for debugging the hook logic, the output is shown in the git output
      - id: run-security-scan
        verbose: true
        args: [--verbose]
      - id: run-personal-data-scan
        verbose: true
        args: [--verbose]