
nlp_engine_name: spacy
models:
-
  lang_code: en
  model_name: en_core_web_sm

ner_model_configuration:
  labels_to_ignore: 
    - ORG
    - ORGANIZATION
    - CARDINAL
    - EVENT
    - FAC
    - LANGUAGE
    - LAW
    - MONEY
    - ORDINAL
    - PERCENT
    - PRODUCT
    - QUANTITY
    - WORK_OF_ART
    - NRP
    - MISC
