global_regex_flags: 26

supported_languages: 
  - en

recognizers: 
  - name: SpacyRecognizer
    type: predefined
    enabled: false # Too many false positives for now
    supported_entities:
      - PERSON
      - LOCATION

  - name: EmailRecognizer
    type: predefined

  - name: PhoneRecognizer
    type: predefined
    supported_regions:
      - GB

  - name: "PostcodeRecognizer"
    supported_language: "en"
    patterns:
      -
          name: "postcode (strong)"
          regex: "([A-Z][A-HJ-Y]?\\d[A-Z\\d]? ?\\d[A-Z]{2}|GIR ?0A{2})"
          score: 1.0
    context:
      - postcode
      - address
    supported_entity: "POSTCODE"