global_regex_flags: 26

supported_languages: 
  - en

recognizers: 
  - name: SpacyRecognizer
    type: predefined
    enabled: false # Too many false positives for now

  - name: EmailRecognizer
    type: predefined

  - name: PhoneRecognizer
    type: predefined
    supported_regions:
      - GB
    leniency: 2
  
  - name: "UKPostcodeRecognizer"
    supported_language: "en"
    patterns:
      -
          name: "postcode (Medium)"
          regex: "(?:^|\\s|\\'|\"|\\=|\\,)([A-Z][A-HJ-Y]?\\d[A-Z\\d]? ?\\d[A-Z]{2}|GIR ?0A{2})(?:$|\\s|\\'|\"|\\,|\\.)"
          score: 0.5
    context:
      - postcode
      - address
      - postal code   
    supported_entity: "UK_POSTCODE"