name: "Organisation ruleset: Python CI"

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/org.python-ci.yml
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main, master, dev]

jobs:
  security-scan:
    # Bandit has its own GitHub Action; however, it always installs the latest version and does not allow version pinning.
    env:
      python-version: "3.13.9"
      bandit-version: "1.9.1"
      results-file: "results.sarif"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      ############# Bandit ##################
      # TODO: Create an ad-hoc DBT Bandit Action
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{env.python-version}}

      - name: Install Bandit
        shell: bash
        run: pip install 'bandit[sarif,toml]==${{env.bandit-version}}'

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Run Bandit
        shell: bash
        run: |
          bandit -r . --confidence-level=high --severity-level=high -f sarif -o ${{env.results-file}} -x './.venv,./tests,./test' || true

      - name: Check for any failures
        id: check-failures
        shell: bash
        run: |
          has_errors=$( jq '.runs[0].results != []' ${{env.results-file}})
          echo "Check failure result: $has_errors"
          echo "has_errors=$has_errors" >> $GITHUB_OUTPUT

      - name: Upload SARIF file
        if: ${{steps.check-failures.outputs.has_errors == 'true'}}
        uses: github/codeql-action/upload-sarif@4e94bd11f71e507f7f87df81788dff88d1dacbfb
        with:
          sarif_file: ${{env.results-file}}

  vulnerability-scan:
    env:
      audit-dir: "audit-reports"
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Git clone the repository"
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - name: "Git clone the standards repository"
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5
        with:
          repository: "uktrade/github-standards"

      - name: "Create audit directory"
        shell: bash
        run: mkdir -p "${{ env.audit-dir }}"
        continue-on-error: true

      - name: "Run Python audit (v${{ vars.PYTHON_VERSION }})"
        uses: ./.github/actions/vulnerability-scan/python
        continue-on-error: true
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          audit-dir: ${{ env.audit-dir }}

      - name: Notify PR creator
        # TODO: Ensure only a single comment is created per PR, updated on each run
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: ./.github/notify/vulnerability
        continue-on-error: true
        with:
          token: ${{ github.token }}
          audit-dir: ${{ env.audit-dir }}
