name: "Single scan: CI"

on:
  pull_request:
    branches: [main, master, dev]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout and read repo files
      security-events: write # Required to upload SARIF files to Security tab
      pull-requests: write # Add comments to PR
      issues: write # Add comments to PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Run Trivy vulnerability scanner
        id: scan
        env:
          TRIVY_DEBUG: true
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          exit-code: 1
          scan-type: "fs"
          # ignore-unfixed: true
          format: "json"
          output: "trivy-common-results.json"
          severity: "UNKNOWN,HIGH,CRITICAL"
          version: v0.68.2
          scanners: "vuln,misconfig"
          # limit-severities-for-sarif: true

      - name: Create template file
        if: failure() && steps.scan.outcome == 'failure'
        run: |
          trivy convert --format template --template "@.github/workflows/trivy-pr-comment.tpl" --output formatted.json trivy-common-results.json

      - name: Report vulnerabilities in PR
        if: failure() && steps.scan.outcome == 'failure'
        shell: bash
        run: |
          echo -n "{\"body\":\"### Trivy fs scan - Vulnerabilities detected\nThe following vulnerabilities of HIGH or CRITICAL severity have been detected in the code. Please resolve these before merging the pull request.\n\n" > summary.json
          cat formatted.json | tr -d '\n' >> summary.json
          echo "\"}" >> summary.json
          echo "$(cat summary.json)"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d @summary.json

      - name: Create sarif file
        if: failure() && steps.scan.outcome == 'failure'
        run: |
          trivy convert --format sarif --output trivy-common-results.sarif trivy-common-results.json

      - name: Upload Trivy scan results to GitHub Security tab
        if: failure() && steps.scan.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7
        with:
          sarif_file: "trivy-common-results.sarif"

      - name: Upload artifact
        if: failure() && steps.scan.outcome == 'failure'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: scan-results
          path: "trivy-common-results.sarif"
